### ISSUE TITLE
Let's make action functions more descriptive?

### ISSUE THREAD

**Issue by nyccto-rapicastillo** [nyc-cto/LPaaS2#44]
https://github.com/nyc-cto/LPaaS2/blob/ebd92adbf1c7106e44f8f79e8b4a90c837eac989/src/components/header.jsx#L27

**Comment by saifulislamdev** [comment]
Great point! Previously updated it to be 
```javascript
const handleMenuClick = () => setExpanded((prevExpanded) => !prevExpanded);
```
